
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaincode-demo
  namespace: dummy-com
  labels: 
    chaincode: chaincode-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      chaincode: chaincode-demo
  template:
    metadata:
      labels:
        chaincode: chaincode-demo
    spec:
      containers:
        - name: chaincode-demo
          image: tommystark/chaincode-as-external-service
          env:
            - name: CHAINCODE_SERVER_ADDRESS
              value: 0.0.0.0:9999
            - name: CHAINCODE_ID
              value: chaincode-as-external-service:aa59fb583d21ef842047bcd5875fb8d960852e0a29f3390b75b1054ccd85fc87
          ports:
            - containerPort: 9999
