resources:
  - services/ordering.service.dummy.com.yaml
  - services/org1.dummy.com/couchdb.yaml
  - services/org1.dummy.com/peer0.yaml
  - services/org2.dummy.com/peer0.yaml
  - services/org3.dummy.com/peer0.yaml
  - services/chaincodes/demo.yaml
  - deployments/orderer0.dummy.com.yaml
  - deployments/orderer1.dummy.com.yaml
  - deployments/orderer2.dummy.com.yaml
  - deployments/org1.dummy.com/couchdb.yaml
  - deployments/org1.dummy.com/peer0.yaml
  - deployments/org2.dummy.com/peer0.yaml
  - deployments/org3.dummy.com/peer0.yaml
  - deployments/chaincodes/demo.yaml
  - deployments/org1.dummy.com/cli.yaml
  - deployments/org2.dummy.com/cli.yaml
