
apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  containers:
    # Replace with your actual workload.
    - name:  busybox
      image: busybox
      args: ['sleep', '100000'] # Do nothing
      volumeMounts:
        - name: chaincode-buildpack
          mountPath: /buildpack
        - name: orderer0-hlf-certificates
          mountPath: /orderer0-hlf-certificates
        - name: orderer1-hlf-certificates
          mountPath: /orderer1-hlf-certificates
        - name: orderer2-hlf-certificates
          mountPath: /orderer2-hlf-certificates
        - name: peer0-org1-hlf-certificates
          mountPath: /peer0-org1-hlf-certificates
        - name: peer0-org2-hlf-certificates
          mountPath: /peer0-org2-hlf-certificates
        - name: peer0-org3-hlf-certificates
          mountPath: /peer0-org3-hlf-certificates
  volumes:
    - name: chaincode-buildpack
      persistentVolumeClaim:
        claimName: chaincode-buildpack
    - name: orderer0-hlf-certificates
      persistentVolumeClaim:
        claimName: orderer0-hlf-certificates
    - name: orderer1-hlf-certificates
      persistentVolumeClaim:
        claimName: orderer1-hlf-certificates
    - name: orderer2-hlf-certificates
      persistentVolumeClaim:
        claimName: orderer2-hlf-certificates
    - name: peer0-org1-hlf-certificates
      persistentVolumeClaim:
        claimName: peer0-org1-hlf-certificates
    - name: peer0-org2-hlf-certificates
      persistentVolumeClaim:
        claimName: peer0-org2-hlf-certificates
    - name: peer0-org3-hlf-certificates
      persistentVolumeClaim:
        claimName: peer0-org3-hlf-certificates
