
apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  containers:
    # Replace with your actual workload.
    - name:  busybox
      image: busybox
      args: ['sleep', '100000'] # Do nothing
      volumeMounts:
        - name: chaincode-buildpack
          mountPath: /debug
  volumes:
    - name: chaincode-buildpack
      persistentVolumeClaim:
        claimName: chaincode-buildpack
